#!/usr/bin/env python3
"""Render engineering fragments and rebuild offline search from current HTML pages."""
import argparse
import json
import re
from html import escape
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class TextParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.text = []

    def handle_data(self, data):
        self.text.append(data)


def plain_text(source):
    parser = TextParser()
    parser.feed(source)
    return re.sub(r"\s+", " ", " ".join(parser.text)).strip()


def render_page(page, body, sidebar, previous_page, next_page):
    headings = re.findall(r'<h2 id="([^"]+)">(.*?)</h2>', body, re.S)
    toc = '<details class="toc"><summary>On this page</summary><ul>'
    toc += ''.join(f'<li><a href="#{escape(anchor)}">{escape(plain_text(title))}</a></li>'
                   for anchor, title in headings)
    toc += '</ul></details>'
    title = escape(page['title'])
    lead = escape(page['lead'])
    navigation = '<nav class="page-nav" aria-label="Engineering chapters">'
    if previous_page:
        navigation += f'<a href="{previous_page["slug"]}.html">← {escape(previous_page["title"])}</a>'
    if next_page:
        navigation += f'<a href="{next_page["slug"]}.html">{escape(next_page["title"])} →</a>'
    navigation += '</nav>'
    current_sidebar = sidebar.replace('aria-current="page"', '')
    current_sidebar = current_sidebar.replace('href="../engineering/index.html"',
        'href="index.html" aria-current="page"')
    return f'''<!doctype html>
<!-- Generated by tools/build_cpp_standard.py; edit engineering/content and pages.json. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} · RPG C++ Engineering Standard</title>
<meta name="description" content="{lead}">
<link rel="stylesheet" href="../site/style.css">
<script defer src="../site/app.js"></script>
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
{current_sidebar}
<div class="layout">
<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="../index.html">Guide home</a><span>/</span><a href="index.html">C++ engineering</a><span>/</span><span>{title}</span></nav>
<article id="main">
<header><div class="eyebrow">RPG · Unreal Engine 5.8.3 · Engineering standard</div><h1>{title}</h1><p class="lead">{lead}</p></header>
{toc}
{body}
{navigation}
</article>
<footer class="page-footer">Engineering standard · 05 October 2026. Examples are focused illustrative fragments, not an implemented game or compile-tested source package. <a href="architecture.html#evidence">Repository evidence</a> · <a href="index.html#maintenance">Maintain this standard</a> · <a href="../sources/cpp-engineering-evidence.json">Evidence record</a></footer>
</div>
</body>
</html>
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated output is stale.')
    args = parser.parse_args()
    pages = json.loads((ROOT / 'engineering/pages.json').read_text())
    chapters = ''.join(f'<section class="card"><h3><a href="{p["slug"]}.html">{escape(p["title"])}</a></h3><p>{escape(p["lead"])}</p></section>' for p in pages)
    index_body = (ROOT / 'engineering/content/index.html').read_text().replace('{{CHAPTER_CARDS}}', chapters)
    documents = [dict(slug='index', title='C++ Development Standards',
                      lead='Simple, explicit Unreal C++ built around this game’s real ownership boundaries.')] + pages
    home = (ROOT / 'index.html').read_text()
    sidebar = re.search(r'<aside class="sidebar">.*?</aside>', home, re.S).group(0)
    sidebar = re.sub(r'href="(?!https?://|#)([^"]+)"', r'href="../\1"', sidebar)
    outputs = {}
    for index, page in enumerate(documents):
        body = index_body if page['slug'] == 'index' else (ROOT / f'engineering/content/{page["slug"]}.html').read_text()
        outputs[ROOT / f'engineering/{page["slug"]}.html'] = render_page(
            page, body, sidebar, documents[index - 1] if index else None,
            documents[index + 1] if index + 1 < len(documents) else None)
    search_path = ROOT / 'site/search-data.js'
    entries = []
    for path in sorted(ROOT.rglob('*.html')):
        if 'content' in path.relative_to(ROOT).parts or path.name == 'original-roadmap.html':
            continue
        source = outputs.get(path, path.read_text())
        article = re.search(r'<article id="main">(.*?)</article>', source, re.S)
        if article is None:
            continue
        title = re.search(r'<h1[^>]*>(.*?)</h1>', article[1], re.S)
        kind = re.search(r'<div class="eyebrow">(.*?)</div>', article[1], re.S)
        entries.append(dict(title=plain_text(title[1]), url=path.relative_to(ROOT).as_posix(),
                            kind=plain_text(kind[1]) if kind else 'Documentation',
                            text=plain_text(article[1])))
    outputs[search_path] = 'window.GUIDE_SEARCH = ' + json.dumps(entries, ensure_ascii=False) + ';\n'
    stale = [path for path, value in outputs.items() if not path.exists() or path.read_text() != value]
    if args.check:
        if stale:
            raise SystemExit('Stale generated output: ' + ', '.join(str(p.relative_to(ROOT)) for p in stale))
        print(f'Generated output current: {len(documents)} engineering pages and search entries.')
        return
    for path, value in outputs.items():
        if path in stale:
            path.write_text(value)
    print(f'Rendered {len(documents)} engineering pages; updated {len(stale)} files.')


if __name__ == '__main__':
    main()
